from pathlib import Path

path = Path("main.py")
text = path.read_text(encoding="utf-8")

if 'APP_VERSION = "0.3.0"' in text:
    print("v0.3.0 ja aplicada")
    raise SystemExit(0)


def replace_once(old: str, new: str, label: str) -> None:
    global text
    if old not in text:
        raise RuntimeError(f"Trecho nao encontrado: {label}")
    text = text.replace(old, new, 1)


replace_once('    QFrame,\n    QHBoxLayout,', '    QFrame,\n    QGridLayout,\n    QHBoxLayout,', 'import QGridLayout')
replace_once('APP_VERSION = "0.2.3"', 'APP_VERSION = "0.3.0"', 'versao')
replace_once('        self.setMinimumSize(1120, 720)', '        self.setMinimumSize(1240, 760)', 'tamanho minimo')

replace_once(
'''class CropLabel(QLabel):\n    cropSelected = Signal(float, float, float, float)\n''',
'''class CropLabel(QLabel):\n    cropSelected = Signal(float, float, float, float)\n    zoomChanged = Signal(int)\n''',
'zoom signal',
)

replace_once(
'''        self._rubber = QRect()\n\n    def sizeHint(self):''',
'''        self._rubber = QRect()\n        self._zoom_factor = 1.0\n\n    def sizeHint(self):''',
'zoom factor',
)

replace_once(
'''    def set_source_pixmap(self, pixmap: Optional[QPixmap]):\n        self._source_pixmap = pixmap\n        self._rubber = QRect()\n        self.update_scaled()\n''',
'''    def set_source_pixmap(self, pixmap: Optional[QPixmap]):\n        self._source_pixmap = pixmap\n        self._rubber = QRect()\n        self._zoom_factor = 1.0\n        self.update_scaled()\n\n    def zoom_in(self):\n        self._zoom_factor = min(3.0, self._zoom_factor + 0.15)\n        self.update_scaled()\n\n    def zoom_out(self):\n        self._zoom_factor = max(0.55, self._zoom_factor - 0.15)\n        self.update_scaled()\n\n    def fit_to_view(self):\n        self._zoom_factor = 1.0\n        self.update_scaled()\n''',
'zoom methods',
)

replace_once(
'''        available = self.contentsRect().adjusted(18, 18, -18, -18)\n        scaled = self._source_pixmap.scaled(\n            available.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation\n        )\n        super().setPixmap(scaled)\n        x = available.x() + (available.width() - scaled.width()) // 2\n        y = available.y() + (available.height() - scaled.height()) // 2\n        self._display_rect = QRect(x, y, scaled.width(), scaled.height())\n        self.update()\n''',
'''        available = self.contentsRect().adjusted(18, 18, -18, -18)\n        if available.width() <= 0 or available.height() <= 0:\n            return\n        fitted = self._source_pixmap.scaled(\n            available.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation\n        )\n        target = QSize(\n            max(1, round(fitted.width() * self._zoom_factor)),\n            max(1, round(fitted.height() * self._zoom_factor)),\n        )\n        scaled = self._source_pixmap.scaled(\n            target, Qt.KeepAspectRatio, Qt.SmoothTransformation\n        )\n        super().setPixmap(scaled)\n        x = available.x() + (available.width() - scaled.width()) // 2\n        y = available.y() + (available.height() - scaled.height()) // 2\n        self._display_rect = QRect(x, y, scaled.width(), scaled.height())\n        percent = max(1, round(100 * scaled.width() / max(1, self._source_pixmap.width())))\n        self.zoomChanged.emit(percent)\n        self.update()\n''',
'zoom rendering',
)

replace_once('        left_title = QLabel("AÇÕES")', '        left_title = QLabel("IMPORTAR")', 'titulo importar')

old_tools = '''        # Todas as ferramentas de edição ficam FORA da área de pré-visualização.\n        edit_tools = QFrame()\n        edit_tools.setObjectName("cropToolsCard")\n        tools_layout = QVBoxLayout(edit_tools)\n        tools_layout.setContentsMargins(9, 9, 9, 9)\n        tools_layout.setSpacing(6)\n        tools_title = QLabel("EDIÇÃO DA PÁGINA")\n        tools_title.setObjectName("fieldLabel")\n        tools_layout.addWidget(tools_title)\n\n        self.btn_crop = QPushButton("⌗  Selecionar corte")\n        self.btn_crop.setObjectName("editPrimary")\n        self.btn_crop.clicked.connect(self.toggle_crop)\n        self.btn_clear_crop = QPushButton("Remover recorte")\n        self.btn_clear_crop.clicked.connect(self.clear_crop)\n        btn_left = QPushButton("↶  Girar à esquerda")\n        btn_left.clicked.connect(lambda: self.rotate_current(-90))\n        btn_right = QPushButton("↷  Girar à direita")\n        btn_right.clicked.connect(lambda: self.rotate_current(90))\n        btn_del = QPushButton("⌫  Excluir página")\n        btn_del.clicked.connect(self.delete_current)\n\n        for b in (self.btn_crop, self.btn_clear_crop, btn_left, btn_right, btn_del):\n            b.setMinimumHeight(34)\n            tools_layout.addWidget(b)\n        left_layout.addWidget(edit_tools)\n'''
new_tools = '''        # Ferramentas de edicao em cards quadrados, sempre fora da pre-visualizacao.\n        tools_title = QLabel("EDIÇÃO DA PÁGINA")\n        tools_title.setObjectName("sectionTitle")\n        left_layout.addWidget(tools_title)\n\n        edit_tools = QFrame()\n        edit_tools.setObjectName("cropToolsCard")\n        tools_grid = QGridLayout(edit_tools)\n        tools_grid.setContentsMargins(0, 0, 0, 0)\n        tools_grid.setHorizontalSpacing(8)\n        tools_grid.setVerticalSpacing(8)\n\n        self.btn_crop = QPushButton("⌗\\nSelecionar\\ncorte")\n        self.btn_crop.setObjectName("toolPrimary")\n        self.btn_crop.clicked.connect(self.toggle_crop)\n        self.btn_clear_crop = QPushButton("▣\\nRemover\\nrecorte")\n        self.btn_clear_crop.setObjectName("toolCropClear")\n        self.btn_clear_crop.clicked.connect(self.clear_crop)\n        btn_left = QPushButton("↶\\nGirar à\\nesquerda")\n        btn_left.setObjectName("toolRotate")\n        btn_left.clicked.connect(lambda: self.rotate_current(-90))\n        btn_right = QPushButton("↷\\nGirar à\\ndireita")\n        btn_right.setObjectName("toolRotate")\n        btn_right.clicked.connect(lambda: self.rotate_current(90))\n        btn_del = QPushButton("⌫   Excluir página")\n        btn_del.setObjectName("toolDelete")\n        btn_del.clicked.connect(self.delete_current)\n\n        for b in (self.btn_crop, self.btn_clear_crop, btn_left, btn_right):\n            b.setMinimumSize(112, 88)\n            b.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)\n        btn_del.setMinimumHeight(54)\n\n        tools_grid.addWidget(self.btn_crop, 0, 0)\n        tools_grid.addWidget(self.btn_clear_crop, 0, 1)\n        tools_grid.addWidget(btn_left, 1, 0)\n        tools_grid.addWidget(btn_right, 1, 1)\n        tools_grid.addWidget(btn_del, 2, 0, 1, 2)\n        left_layout.addWidget(edit_tools)\n'''
replace_once(old_tools, new_tools, 'cards de edicao')

old_head = '''        center_head = QHBoxLayout()\n        preview_title = QLabel("PRÉ-VISUALIZAÇÃO")\n        preview_title.setObjectName("sectionTitle")\n        center_head.addWidget(preview_title)\n        center_head.addStretch(1)\n        self.page_indicator = QLabel("Nenhuma página selecionada")\n        self.page_indicator.setObjectName("mutedText")\n        center_head.addWidget(self.page_indicator)\n        center_layout.addLayout(center_head)\n\n        self.preview = CropLabel()\n        self.preview.setObjectName("previewArea")\n        self.preview.cropSelected.connect(self.apply_crop)\n        center_layout.addWidget(self.preview, 1)\n'''
new_head = '''        center_head = QHBoxLayout()\n        preview_title = QLabel("PRÉ-VISUALIZAÇÃO")\n        preview_title.setObjectName("sectionTitle")\n        center_head.addWidget(preview_title)\n        center_head.addStretch(1)\n        self.page_indicator = QLabel("Nenhuma página selecionada")\n        self.page_indicator.setObjectName("mutedText")\n        self.page_indicator.setMaximumWidth(250)\n        center_head.addWidget(self.page_indicator)\n\n        btn_zoom_out = QPushButton("−")\n        btn_zoom_out.setObjectName("zoomButton")\n        btn_zoom_out.setFixedSize(38, 34)\n        self.zoom_label = QLabel("100%")\n        self.zoom_label.setObjectName("zoomValue")\n        self.zoom_label.setAlignment(Qt.AlignCenter)\n        self.zoom_label.setMinimumWidth(50)\n        btn_zoom_in = QPushButton("+")\n        btn_zoom_in.setObjectName("zoomButton")\n        btn_zoom_in.setFixedSize(38, 34)\n        btn_fit = QPushButton("⛶  Ajustar")\n        btn_fit.setObjectName("zoomFit")\n        btn_fit.setMinimumHeight(34)\n        center_head.addWidget(btn_zoom_out)\n        center_head.addWidget(self.zoom_label)\n        center_head.addWidget(btn_zoom_in)\n        center_head.addWidget(btn_fit)\n        center_layout.addLayout(center_head)\n\n        self.preview = CropLabel()\n        self.preview.setObjectName("previewArea")\n        self.preview.cropSelected.connect(self.apply_crop)\n        self.preview.zoomChanged.connect(lambda value: self.zoom_label.setText(f"{value}%"))\n        btn_zoom_out.clicked.connect(self.preview.zoom_out)\n        btn_zoom_in.clicked.connect(self.preview.zoom_in)\n        btn_fit.clicked.connect(self.preview.fit_to_view)\n        center_layout.addWidget(self.preview, 1)\n'''
replace_once(old_head, new_head, 'controles de zoom')

replace_once(
'''        pages_head.addWidget(QLabel("arraste para reordenar"))\n        pages_head.addStretch(1)\n        self.pages_count = QLabel("0 página(s)")''',
'''        reorder_hint = QLabel("Arraste para reordenar")\n        reorder_hint.setObjectName("mutedText")\n        pages_head.addWidget(reorder_hint)\n        pages_head.addStretch(1)\n        btn_add_pages = QPushButton("＋  Adicionar páginas")\n        btn_add_pages.setObjectName("pagesAdd")\n        btn_add_pages.clicked.connect(self.add_images)\n        pages_head.addWidget(btn_add_pages)\n        self.pages_count = QLabel("0 página(s)")''',
'adicionar paginas',
)

# Textos do botao de recorte precisam preservar o novo formato em todas as mudancas de estado.
text = text.replace('self.btn_crop.setText("⌗  Selecionar corte")', 'self.btn_crop.setText("⌗\\nSelecionar\\ncorte")')
text = text.replace('self.btn_crop.setText("Cancelar seleção" if self.crop_mode else "⌗  Selecionar corte")', 'self.btn_crop.setText("×\\nCancelar\\nseleção" if self.crop_mode else "⌗\\nSelecionar\\ncorte")')

old_theme_start = '''            * { font-family: 'Segoe UI'; font-size: 13px; }\n            QMainWindow, #appRoot { background:#0b1220; color:#eef4ff; }\n            #header { background:#101b2b; border-bottom:1px solid #26384f; }\n            #appTitle { font-size:24px; font-weight:700; color:#f5f8ff; }\n            #appSubtitle, #mutedText { color:#8fa3bd; }\n            #panel, #pagesPanel { background:#111d2c; border:1px solid #263950; border-radius:12px; }\n            #sectionTitle { color:#c7d3e3; font-size:13px; font-weight:700; letter-spacing:1px; }\n            QPushButton { background:#1a2a3e; color:#edf4ff; border:1px solid #314861; border-radius:8px; padding:9px 12px; }\n            QPushButton:hover { background:#233951; border-color:#47709a; }\n            QPushButton:pressed { background:#152639; }\n            #primaryAction, #topPrimary, #generate, #editPrimary { background:#1769d2; border:1px solid #2c82ea; font-weight:700; }\n            #primaryAction:hover, #topPrimary:hover, #generate:hover, #editPrimary:hover { background:#2379e5; }\n            #secondaryAction { text-align:left; padding-left:16px; }\n            #topAction, #topPrimary { min-height:34px; }\n            #dropZone { background:#0e1826; color:#aebed1; border:1px dashed #667b93; border-radius:10px; padding:10px; font-size:13px; }\n            #tipBox { color:#a3b4c8; background:#142235; border:1px solid #28405a; border-radius:8px; padding:8px; font-size:12px; }\n            #previewArea { background:#0b1420; border:1px solid #263a51; border-radius:10px; }\n            #editBar { background:#0e1826; border:1px solid #263950; border-radius:9px; }\n            #settingsCard, #cropToolsCard { background:#152235; border:1px solid #2a4058; border-radius:10px; }\n'''
new_theme_start = '''            * { font-family: 'Segoe UI Variable', 'Segoe UI'; font-size: 13px; }\n            QMainWindow, #appRoot { background:#07111e; color:#f2f6ff; }\n            #header { background:#091522; border-bottom:1px solid #20344b; }\n            #appTitle { font-size:25px; font-weight:700; color:#f8fbff; }\n            #appSubtitle, #mutedText { color:#8ea4bf; }\n            #panel, #pagesPanel { background:#0d1927; border:1px solid #223950; border-radius:14px; }\n            #sectionTitle { color:#d8e4f2; font-size:13px; font-weight:700; letter-spacing:1px; border-left:3px solid #2478ff; padding-left:8px; }\n            QPushButton { background:#111f30; color:#edf5ff; border:1px solid #2b425b; border-radius:10px; padding:9px 12px; }\n            QPushButton:hover { background:#172b40; border-color:#4f79a5; }\n            QPushButton:pressed { background:#0d1a28; }\n            #primaryAction { background:#176fe0; border:1px solid #2f8cff; font-weight:700; }\n            #primaryAction:hover { background:#2580ee; }\n            #topPrimary, #generate { background:qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #176fff, stop:1 #7527ff); border:1px solid #6d63ff; font-weight:700; }\n            #topPrimary:hover, #generate:hover { background:qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #2a7cff, stop:1 #873cff); }\n            #secondaryAction { text-align:left; padding-left:16px; }\n            #topAction, #topPrimary { min-height:36px; }\n            #dropZone { background:#091522; color:#b3c4d8; border:1px dashed #56718e; border-radius:12px; padding:10px; font-size:13px; }\n            #tipBox { color:#aabbd0; background:#101e2e; border:1px solid #263f58; border-radius:10px; padding:8px; font-size:12px; }\n            #previewArea { background:#080f19; border:1px solid #1f344b; border-radius:12px; }\n            #settingsCard { background:#101d2d; border:1px solid #263d55; border-radius:12px; }\n            #cropToolsCard { background:transparent; border:none; }\n            #toolPrimary, #toolCropClear, #toolRotate { background:#101d2d; border:1px solid #2a425b; border-radius:12px; font-weight:600; padding:8px; }\n            #toolPrimary { color:#76aaff; }\n            #toolCropClear { color:#ff8a65; }\n            #toolRotate { color:#54dda1; }\n            #toolPrimary:hover, #toolCropClear:hover, #toolRotate:hover { background:#17283b; border-color:#4b7096; }\n            #toolDelete { background:#151d29; color:#ff6b72; border:1px solid #48303a; border-radius:12px; font-weight:600; }\n            #toolDelete:hover { background:#251b24; border-color:#7a3948; }\n            #zoomButton, #zoomFit, #pagesAdd { background:#101d2d; border:1px solid #2a425b; border-radius:9px; padding:6px 10px; }\n            #zoomButton:hover, #zoomFit:hover, #pagesAdd:hover { background:#172a3e; border-color:#4a739e; }\n            #zoomValue { color:#dbe8f7; font-weight:600; }\n'''
replace_once(old_theme_start, new_theme_start, 'tema moderno')

text = text.replace('#coverPreview { background:#0b1420; border:1px solid #263a51; border-radius:7px; }', '#coverPreview { background:#080f19; border:1px solid #233a52; border-radius:10px; }')
text = text.replace('QListWidget { background:#0d1724; border:1px solid #253a51; border-radius:9px; padding:5px; outline:0; }', 'QListWidget { background:#08131f; border:1px solid #21374d; border-radius:11px; padding:6px; outline:0; }')
text = text.replace('QListWidget::item { background:#152235; border:1px solid #2a4058; border-radius:8px; padding:5px; margin:2px; }', 'QListWidget::item { background:#101f30; border:1px solid #2b435c; border-radius:10px; padding:5px; margin:3px; }')
text = text.replace('QListWidget::item:selected { background:#163e70; border:2px solid #2f8cff; color:white; }', 'QListWidget::item:selected { background:#153f74; border:2px solid #2f86ff; color:white; }')

path.write_text(text, encoding="utf-8")
print("Editor de PDF Windows v0.3.0 aplicado")
